# Generated by Django 2.0.2 on 2019-01-22 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'managed': True},
        ),
    ]
