# Generated by Django 2.0.2 on 2019-01-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_auto_20190122_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='zonas')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
