# Generated by Django 2.0.2 on 2019-01-22 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_indicacion_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='indicaciones',
            field=models.ManyToManyField(blank=True, related_name='indicacionlist', to='fichas.Indicacion'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='zonap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fichas.Zona'),
        ),
    ]
