# Generated by Django 2.0.2 on 2019-01-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0004_auto_20190122_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntuar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, help_text='12345678A', max_length=9, null=True, unique=True)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='indicacion',
            options={'managed': True, 'ordering': ('nombre',)},
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={'managed': True, 'ordering': ('nombre',)},
        ),
        migrations.AddField(
            model_name='inventario',
            name='puntuacion',
            field=models.ManyToManyField(to='fichas.Puntuar'),
        ),
    ]
