# Generated by Django 2.0.2 on 2019-01-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0005_auto_20190125_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntuar',
            name='dni',
            field=models.CharField(blank=True, help_text='12345678A', max_length=9, null=True),
        ),
    ]
