# Generated by Django 2.0.2 on 2019-01-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0006_auto_20190125_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='puntuacion',
        ),
        migrations.AddField(
            model_name='puntuar',
            name='ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notasproducto', to='fichas.Inventario'),
        ),
    ]
