# Generated by Django 2.0.2 on 2019-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0007_auto_20190127_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntuar',
            name='ficha',
        ),
        migrations.AddField(
            model_name='inventario',
            name='puntuacion',
            field=models.ManyToManyField(to='fichas.Puntuar'),
        ),
    ]
