# Generated by Django 2.0.2 on 2019-01-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0008_auto_20190127_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='media',
            field=models.CharField(blank=True, default='N/P', max_length=5, null=True),
        ),
    ]
