# Generated by Django 2.0.2 on 2019-01-29 09:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0010_remove_inventario_media'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='inventario',
            managers=[
                ('media', django.db.models.manager.Manager()),
            ],
        ),
    ]
