# Generated by Django 2.0.2 on 2019-01-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0011_auto_20190129_1000'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='inventario',
            managers=[
            ],
        ),
    ]
