# Generated by Django 2.0.2 on 2019-02-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0013_inventario_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='indicaciones',
            field=models.ManyToManyField(to='fichas.Indicacion'),
        ),
    ]
